/*
 * Click nbfs://nbhost/Sy
stemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package MibG12;

import java.util.ArrayList;
import javax.swing.JOptionPane;
import oru.inf.InfDB;
import oru.inf.InfException;

/**
 *
 * @author 46737
 */
public class AdminKontorsChef extends javax.swing.JFrame {

    private static InfDB idb;
    private String agent;

    /**
     * Creates new form AdminKontorsChef
     */
    public AdminKontorsChef(InfDB idb, String agent) {
        this.idb = idb;
        this.agent = agent;
        initComponents();
        FyllaComboBox.laggTillAgent(cbAgenter);
        visaNuvarandeChef();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnOk = new javax.swing.JButton();
        btnTillbaka = new javax.swing.JButton();
        jLabelAgent = new javax.swing.JLabel();
        jLabelOmrade = new javax.swing.JLabel();
        jLabelHarAndrats = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        cbAgenter = new javax.swing.JComboBox<>();
        jLabel3 = new javax.swing.JLabel();
        lblNuvChef = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnOk.setText("Ändra");
        btnOk.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnOkActionPerformed(evt);
            }
        });

        btnTillbaka.setText("Tillbaka");
        btnTillbaka.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTillbakaActionPerformed(evt);
            }
        });

        jLabelAgent.setText("Namn");

        jLabelOmrade.setText("Kontorsbeteckning:");

        jLabel1.setText("Örebrokontoret");

        jLabel2.setText("Vänligen mata in namnet på den nya kontorschefen nedan");

        cbAgenter.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Välj:" }));

        jLabel3.setText("Nuvarande kontorschef:");

        lblNuvChef.setText("agent");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                            .addGap(59, 59, 59)
                            .addComponent(btnTillbaka)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnOk, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addContainerGap()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addComponent(jLabelAgent, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabelOmrade, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 137, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(jLabelHarAndrats, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(jLabel1)
                                .addComponent(cbAgenter, 0, 92, Short.MAX_VALUE)
                                .addComponent(lblNuvChef, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 326, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(44, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addComponent(jLabel2)
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelAgent)
                    .addComponent(cbAgenter, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(33, 33, 33)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelOmrade)
                    .addComponent(jLabel1))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabelHarAndrats, javax.swing.GroupLayout.DEFAULT_SIZE, 31, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel3)
                            .addComponent(lblNuvChef))
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnTillbaka)
                    .addComponent(btnOk))
                .addGap(18, 18, 18))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnOkActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnOkActionPerformed
        // Metod för att validera och fastställa val av ny kontorschef

        try {

            String agentNamn = cbAgenter.getSelectedItem().toString();

            String namnID = "select Agent_ID from agent where Namn = '" + agentNamn + "'";
            String agentAttTaBort = "select Agent_ID from kontorschef";

            String svar1 = idb.fetchSingle(namnID);
            String svar2 = idb.fetchSingle(agentAttTaBort);

            String taBort = "delete from kontorschef where Agent_ID = '" + svar2 + "'";
            String nyChef = "insert into kontorschef values(" + svar1 + "," + "'Örebrokontoret')";

            if (svar1.equals(svar2)) {

                JOptionPane.showMessageDialog(null, "Den valda agenter är redan kontorschef! Vänligen välj en annan agent!");

            } else {
                idb.fetchSingle(taBort);
                idb.fetchSingle(nyChef);
                jLabelHarAndrats.setText("Kontorschefen har ändrats till " + agentNamn + "!");
                cbAgenter.setSelectedIndex(0);  
            }
        } catch (InfException ie) {
            JOptionPane.showMessageDialog(null, "Databasfel");
        }

    }//GEN-LAST:event_btnOkActionPerformed

    private void btnTillbakaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTillbakaActionPerformed
        // Metod för att komma tillbaka till HuvudMenyAdmin
        HuvudMenyAdmin huvudMenyAdmin = new HuvudMenyAdmin(idb, agent);
        huvudMenyAdmin.setVisible(true);
        dispose();

    }//GEN-LAST:event_btnTillbakaActionPerformed

    public void visaNuvarandeChef ()
    {
        try {
                String fraga = "Select namn from agent where agent_id = (Select agent_id from kontorschef)";
                String svar = idb.fetchSingle(fraga);
                lblNuvChef.setText(svar);
                }
        catch (InfException e)
        {
            JOptionPane.showMessageDialog(null, "Databasfel");
        }
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnOk;
    private javax.swing.JButton btnTillbaka;
    private javax.swing.JComboBox<String> cbAgenter;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabelAgent;
    private javax.swing.JLabel jLabelHarAndrats;
    private javax.swing.JLabel jLabelOmrade;
    private javax.swing.JLabel lblNuvChef;
    // End of variables declaration//GEN-END:variables
}
