/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package MibG12;

import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import oru.inf.InfDB;
import oru.inf.InfException;

/**
 *
 * @author Victo
 */
public class AgentInfo extends javax.swing.JFrame {

  private static InfDB idb;
  private String nuvarandeAgent;
  private String nuvarandeUtomjording;
  private HuvudMenyAgent huvudMenyAgent; 
  private HuvudMenyUtomjording huvudMenyUtomjording;       
    
    /**
     * Creates new form AgentInfo
     */
    public AgentInfo(InfDB idb) {
        initComponents();
        this.idb = idb;
        huvudMenyAgent = null;
        huvudMenyUtomjording = null;
    }

    AgentInfo(MibG12.Startklass idb) {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblBetackningRubrik = new javax.swing.JLabel();
        lblTelefonRubrik = new javax.swing.JLabel();
        lblAdminstatusRubrik = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        lblAnstallningsDatumRubrik = new javax.swing.JLabel();
        lblOmradeRubrik = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        lblAgentNamn = new javax.swing.JLabel();
        lblAgentTelefon = new javax.swing.JLabel();
        lblAdminStatus = new javax.swing.JLabel();
        lblAnstallningsDatum = new javax.swing.JLabel();
        lblOmrade = new javax.swing.JLabel();
        lblIdNummerKol = new javax.swing.JLabel();
        lblIdNummer = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblBetackningRubrik.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblBetackningRubrik.setText("Betäckning:");

        lblTelefonRubrik.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblTelefonRubrik.setText("Telefon:");

        lblAdminstatusRubrik.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblAdminstatusRubrik.setText("Adminstatus:");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel4.setText("Agent information");

        jLabel5.setIcon(new javax.swing.ImageIcon("C:\\Users\\Victo\\OneDrive\\Skrivbord\\Tommy-lee-jones-as-agent-k-in-men-in-black.jpg")); // NOI18N
        jLabel5.setText("jLabel5");

        lblAnstallningsDatumRubrik.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblAnstallningsDatumRubrik.setText("Anställningsdatum:");

        lblOmradeRubrik.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblOmradeRubrik.setText("Område:");

        jButton1.setText("Tillbaka");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        lblAgentNamn.setText("Namn");

        lblAgentTelefon.setText("Telefonummer");

        lblAdminStatus.setText("Adminstatus");

        lblAnstallningsDatum.setText("Anställningsdatum");

        lblOmrade.setText("Område");

        lblIdNummerKol.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblIdNummerKol.setText("ID-Nummer:");

        lblIdNummer.setText("ID");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 260, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(69, 69, 69)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblBetackningRubrik, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblTelefonRubrik, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 59, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblAgentNamn, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblAdminStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblAgentTelefon, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(143, 143, 143))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblAdminstatusRubrik, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(lblAnstallningsDatumRubrik, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(lblOmradeRubrik, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(lblIdNummerKol, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(lblIdNummer, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(lblOmrade, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(lblAnstallningsDatum, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE))))
                                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(83, 83, 83)
                        .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
            .addGroup(layout.createSequentialGroup()
                .addGap(250, 250, 250)
                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 227, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel4)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(93, 93, 93)
                                .addComponent(lblAdminstatusRubrik)
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lblAnstallningsDatumRubrik)
                                    .addComponent(lblAnstallningsDatum)))
                            .addGroup(layout.createSequentialGroup()
                                .addGap(25, 25, 25)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lblBetackningRubrik)
                                    .addComponent(lblAgentNamn))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lblTelefonRubrik)
                                    .addComponent(lblAgentTelefon))
                                .addGap(18, 18, 18)
                                .addComponent(lblAdminStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblOmradeRubrik)
                            .addComponent(lblOmrade))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblIdNummerKol)
                            .addComponent(lblIdNummer))))
                .addGap(44, 44, 44)
                .addComponent(jButton1)
                .addContainerGap(33, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void setHuvudMenyAgent ()
    {
        HuvudMenyAgent hMA = new HuvudMenyAgent(idb, nuvarandeAgent);
        huvudMenyAgent = hMA;
    }
    
    public void setHuvudMenyUtomjording ()
    {
        HuvudMenyUtomjording hMU = new HuvudMenyUtomjording(idb, nuvarandeUtomjording);
        huvudMenyUtomjording = hMU;
    }
    
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        if (huvudMenyAgent !=null)
        {
        HuvudMenyAgent hMA = new HuvudMenyAgent(idb, nuvarandeAgent);
        hMA.setNuvarandeAgent(nuvarandeAgent);
        hMA.setHuvudText(nuvarandeAgent);
        hMA.setVisible(true);
        dispose();
        }
        
        else if (huvudMenyUtomjording !=null)
        {
            HuvudMenyUtomjording hMU = new HuvudMenyUtomjording(idb, nuvarandeUtomjording);
            hMU.setNuvarandeUtomjording(nuvarandeUtomjording);
            hMU.setVisible(true);
            hMU.setValkommenUtomjording();
            dispose();
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    public void setNuvarandeAgent (String nuvarandeAgent)
    {
        this.nuvarandeAgent = nuvarandeAgent;
    }
    
    public void setNuvarandeUtomjording (String nuvarandeUtomjording)
    {
        this.nuvarandeUtomjording = nuvarandeUtomjording;
    }
       
    public void showInfo (String namn)
    {
        try {
       String fraga1 = "Select namn from agent where namn = '" + namn + "'";
       String fraga2 = "Select telefon from agent where namn= '" + namn + "'";
       String fraga3 = "Select administrator from agent where namn = '" + namn + "'";
       String fraga4 = "Select anstallningsdatum from agent where namn = '" + namn + "'";
       String fraga5 = "Select benamning from omrade where Omrades_ID = (Select omrade from agent where namn = '" + namn + "')";
       String fraga6 = "SELECT `Agent_ID` FROM agent where namn = '" + namn + "'";
        
       String svar1 = idb.fetchSingle(fraga1);
       String svar2 = idb.fetchSingle(fraga2);
       String svar3 = idb.fetchSingle(fraga3);
       String svar4 = idb.fetchSingle(fraga4);
       String svar5 = idb.fetchSingle(fraga5);
       String svar6 = idb.fetchSingle(fraga6);
       
       String adminSvar = Validering.setAdminStatus(svar3);
       
       lblAgentNamn.setText(svar1);
       lblAgentTelefon.setText(svar2);
       lblAdminStatus.setText(adminSvar);
       lblAnstallningsDatum.setText(svar4);
       lblOmrade.setText(svar5);
       lblIdNummer.setText(svar6);
       
        }
        catch (InfException ex) {
            Logger.getLogger(InloggningsTyp.class.getName()).log(Level.SEVERE, null, ex);
            System.out.println("Ett fel har uppstått " + ex);
        }
    }
    


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel lblAdminStatus;
    private javax.swing.JLabel lblAdminstatusRubrik;
    private javax.swing.JLabel lblAgentNamn;
    private javax.swing.JLabel lblAgentTelefon;
    private javax.swing.JLabel lblAnstallningsDatum;
    private javax.swing.JLabel lblAnstallningsDatumRubrik;
    private javax.swing.JLabel lblBetackningRubrik;
    private javax.swing.JLabel lblIdNummer;
    private javax.swing.JLabel lblIdNummerKol;
    private javax.swing.JLabel lblOmrade;
    private javax.swing.JLabel lblOmradeRubrik;
    private javax.swing.JLabel lblTelefonRubrik;
    // End of variables declaration//GEN-END:variables
}
