/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package MibG12;

import oru.inf.InfDB;
import java.util.ArrayList;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import oru.inf.InfException;

/**
 *
 * @author Victo
 */
public class AndraInfoOmAlien extends javax.swing.JFrame {

    InfDB idb;
    String nuvarandeAgent;
    String nuvarandeUtomjording;
    VisaInfoOmAlien visaInfoOmAlien;
    
    /**
     * Creates new form AndraInfoOmAlien
     */
    public AndraInfoOmAlien(InfDB idb, String nuvarandeAgent, String nuvarandeUtomjording) {
        initComponents();
        this.idb = idb;
        this.nuvarandeAgent = nuvarandeAgent;
        this.nuvarandeUtomjording = nuvarandeUtomjording;
        visaInfoOmAlien = new VisaInfoOmAlien (idb, nuvarandeAgent);
        visaInfoOmAlien.showInfo(nuvarandeAgent);
        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        HuvudText = new javax.swing.JLabel();
        lblNamnRubrik = new javax.swing.JLabel();
        lblRegDatumRubrik = new javax.swing.JLabel();
        lblTelefonRubrik = new javax.swing.JLabel();
        lblLosenordRubrik = new javax.swing.JLabel();
        lblPlatsRubrik = new javax.swing.JLabel();
        lblNamn = new javax.swing.JLabel();
        lblRas = new javax.swing.JLabel();
        lblRegDatum = new javax.swing.JLabel();
        lblTelefon = new javax.swing.JLabel();
        lblLosen = new javax.swing.JLabel();
        lblPlats = new javax.swing.JLabel();
        txtNamn = new javax.swing.JTextField();
        txtRas = new javax.swing.JTextField();
        txtTelefon = new javax.swing.JTextField();
        txtRegDatum = new javax.swing.JTextField();
        txtPlats = new javax.swing.JTextField();
        lblRasRubrik = new javax.swing.JLabel();
        txtAnsvarigAgent = new javax.swing.JTextField();
        btnAndraRas = new javax.swing.JButton();
        btnAndraNamn = new javax.swing.JButton();
        btnAndraRegDatum = new javax.swing.JButton();
        btnAndraPlats = new javax.swing.JButton();
        btnAndraTelefon = new javax.swing.JButton();
        btnAndraLosenord = new javax.swing.JButton();
        lblInfoRubrik = new javax.swing.JLabel();
        lblIdNummerRubrik = new javax.swing.JLabel();
        lblID = new javax.swing.JLabel();
        btnTillbakaTillHM = new javax.swing.JButton();
        btnTillbaka = new javax.swing.JButton();
        iblAnsvarigAgentRubrik = new javax.swing.JLabel();
        lblAnsvarigAgent = new javax.swing.JLabel();
        btnAndraAnsvarigAgent = new javax.swing.JButton();
        txtLosenord = new javax.swing.JTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        HuvudText.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        HuvudText.setText("Information om Alien");

        lblNamnRubrik.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblNamnRubrik.setText("Namn: ");

        lblRegDatumRubrik.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblRegDatumRubrik.setText("Registreringsdatum: ");

        lblTelefonRubrik.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblTelefonRubrik.setText("Telefon: ");

        lblLosenordRubrik.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblLosenordRubrik.setText("Lösenord:");

        lblPlatsRubrik.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblPlatsRubrik.setText("Plats:");

        lblNamn.setText("Hehe");

        txtNamn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNamnActionPerformed(evt);
            }
        });

        txtRas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtRasActionPerformed(evt);
            }
        });

        lblRasRubrik.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblRasRubrik.setText("Ras");

        txtAnsvarigAgent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtAnsvarigAgentActionPerformed(evt);
            }
        });

        btnAndraRas.setText("Ändra");
        btnAndraRas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAndraRasActionPerformed(evt);
            }
        });

        btnAndraNamn.setText("Ändra");
        btnAndraNamn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAndraNamnActionPerformed(evt);
            }
        });

        btnAndraRegDatum.setText("Ändra");
        btnAndraRegDatum.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAndraRegDatumActionPerformed(evt);
            }
        });

        btnAndraPlats.setText("Ändra");
        btnAndraPlats.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAndraPlatsActionPerformed(evt);
            }
        });

        btnAndraTelefon.setText("Ändra");
        btnAndraTelefon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAndraTelefonActionPerformed(evt);
            }
        });

        btnAndraLosenord.setText("Ändra");
        btnAndraLosenord.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAndraLosenordActionPerformed(evt);
            }
        });

        lblInfoRubrik.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblInfoRubrik.setText("Ny Information");

        lblIdNummerRubrik.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblIdNummerRubrik.setText("ID-Nummer:");

        btnTillbakaTillHM.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        btnTillbakaTillHM.setText("Tillbaka till huvudmeny");
        btnTillbakaTillHM.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTillbakaTillHMActionPerformed(evt);
            }
        });

        btnTillbaka.setText("Tillbaka");
        btnTillbaka.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTillbakaActionPerformed(evt);
            }
        });

        iblAnsvarigAgentRubrik.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        iblAnsvarigAgentRubrik.setText("Ansvarig Agent:");

        btnAndraAnsvarigAgent.setText("Ändra");
        btnAndraAnsvarigAgent.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAndraAnsvarigAgentActionPerformed(evt);
            }
        });

        txtLosenord.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtLosenordActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnTillbaka, javax.swing.GroupLayout.PREFERRED_SIZE, 102, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(59, 59, 59)
                .addComponent(btnTillbakaTillHM)
                .addGap(118, 118, 118))
            .addGroup(layout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(lblTelefonRubrik, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblTelefon, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(lblLosenordRubrik, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lblLosen, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(25, 25, 25)
                                    .addComponent(HuvudText, javax.swing.GroupLayout.PREFERRED_SIZE, 162, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(lblRasRubrik, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(lblNamnRubrik, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE))
                                    .addGap(49, 49, 49)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(lblNamn, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 64, Short.MAX_VALUE)
                                        .addComponent(lblRas, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                                .addComponent(lblIdNummerRubrik, javax.swing.GroupLayout.PREFERRED_SIZE, 87, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(iblAnsvarigAgentRubrik)
                                    .addGap(39, 39, 39)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                        .addComponent(lblID, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(lblAnsvarigAgent, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE))))
                            .addGap(23, 23, 23)))
                    .addComponent(lblPlatsRubrik, javax.swing.GroupLayout.PREFERRED_SIZE, 73, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblRegDatumRubrik, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(133, 133, 133)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblPlats, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblRegDatum, javax.swing.GroupLayout.PREFERRED_SIZE, 83, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 33, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(lblInfoRubrik, javax.swing.GroupLayout.PREFERRED_SIZE, 107, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtPlats, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtRas, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtNamn, javax.swing.GroupLayout.PREFERRED_SIZE, 115, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtRegDatum, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtTelefon, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtAnsvarigAgent, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(txtLosenord, javax.swing.GroupLayout.PREFERRED_SIZE, 113, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(49, 49, 49)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnAndraPlats, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAndraRegDatum, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAndraRas, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAndraNamn, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAndraTelefon, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAndraLosenord, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnAndraAnsvarigAgent, javax.swing.GroupLayout.PREFERRED_SIZE, 78, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(47, 47, 47))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblInfoRubrik)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(txtNamn, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblRas)
                                    .addComponent(lblRasRubrik)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(txtRas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(btnAndraRas)))
                                .addGap(26, 26, 26)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(lblRegDatumRubrik)
                                        .addComponent(lblRegDatum))
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(txtRegDatum, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(btnAndraRegDatum)))
                                .addGap(24, 24, 24)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(lblPlatsRubrik)
                                        .addComponent(lblPlats))
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(txtPlats, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(btnAndraPlats)))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(lblTelefonRubrik)
                                        .addComponent(lblTelefon))
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                        .addComponent(txtTelefon, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addComponent(btnAndraTelefon)))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lblLosenordRubrik)
                                    .addComponent(lblLosen))
                                .addGap(24, 24, 24)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(lblIdNummerRubrik)
                                    .addComponent(lblID)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnAndraNamn)
                                .addGap(201, 201, 201)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(btnAndraLosenord)
                                    .addComponent(txtLosenord, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(HuvudText)
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblNamnRubrik)
                            .addComponent(lblNamn))))
                .addGap(36, 36, 36)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(iblAnsvarigAgentRubrik)
                    .addComponent(lblAnsvarigAgent)
                    .addComponent(btnAndraAnsvarigAgent)
                    .addComponent(txtAnsvarigAgent, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 14, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnTillbaka, javax.swing.GroupLayout.DEFAULT_SIZE, 29, Short.MAX_VALUE)
                    .addComponent(btnTillbakaTillHM, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtNamnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNamnActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNamnActionPerformed

    private void txtRasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtRasActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtRasActionPerformed

    private void txtAnsvarigAgentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAnsvarigAgentActionPerformed
        
        
    }//GEN-LAST:event_txtAnsvarigAgentActionPerformed

    private void btnTillbakaTillHMActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTillbakaTillHMActionPerformed
        HuvudMenyAgent hMA = new HuvudMenyAgent (idb, nuvarandeAgent);
        hMA.setHuvudText(nuvarandeAgent);
        hMA.setVisible(true);
        dispose();
    }//GEN-LAST:event_btnTillbakaTillHMActionPerformed

    private void btnTillbakaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTillbakaActionPerformed
        ValjAlienFromAgentHuvudMeny vAFAHM = new ValjAlienFromAgentHuvudMeny(idb, nuvarandeAgent);
        vAFAHM.setVisible(true);
        vAFAHM.setVisaAndraText();
        dispose();
    }//GEN-LAST:event_btnTillbakaActionPerformed

    private void btnAndraNamnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAndraNamnActionPerformed
        
        String nyttNamn = txtNamn.getText();
        String gammaltNamn = lblNamn.getText();
        
        boolean namnetSamma = Validering.stringFinns(nyttNamn, gammaltNamn);
        boolean textRutaArTom = Validering.textRutaArTom(nyttNamn);
        boolean namnetEjAnvant = kollaNamn(nyttNamn);
        
        if (textRutaArTom == false) {
            
            if (namnetEjAnvant == false) {
                
                if (namnetSamma == false) {
                    
                    try {
                        String fraga = "Update Alien set namn = '" + nyttNamn + "' where namn = '" + nuvarandeUtomjording + "'";
                        String svar = idb.fetchSingle(fraga);
                        JOptionPane.showMessageDialog(null, "Namnet har ändrats!");
                        setNuvarandeUtomjording(nyttNamn);
                        showInfo(nuvarandeUtomjording);
                        txtNamn.setText("");
                    } catch (InfException ex) {
                        JOptionPane.showMessageDialog(null, "Någonting gick fel, vänligen prova igen");
                        txtNamn.setText("");
                    }
                } else {
                    JOptionPane.showMessageDialog(null, "Namnet har inte ändrats, Vänligen skriv in ett annat namn!");
                    txtNamn.setText("");
                }
            } else {
                JOptionPane.showMessageDialog(null, "Namnet används redan av en annan utomjording. Vänligen skriv ett annat namn!");
                txtNamn.setText("");
            }
            
        } else {
            txtNamn.setText("");
        }


    }//GEN-LAST:event_btnAndraNamnActionPerformed

    private void btnAndraRegDatumActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAndraRegDatumActionPerformed

        String gammaltDatum = lblRegDatum.getText();
        String nyttDatum = txtRegDatum.getText();
        boolean datumKorrekt = Validering.stringFinns(gammaltDatum, nyttDatum);
        boolean textRutaArTom = Validering.textRutaArTom(gammaltDatum);

        if (textRutaArTom == false)
        {
        
        if (datumKorrekt == false) {

            try {
                String fraga = "Update Alien set registreringsdatum = '" + nyttDatum + "' where namn = '" + nuvarandeUtomjording + "'";
                String svar = idb.fetchSingle(fraga);
                JOptionPane.showMessageDialog(null, "Registreingsdatumet har ändrats!");
                txtRegDatum.setText("");
                showInfo(nuvarandeUtomjording);
            } catch (InfException ex) {
                JOptionPane.showMessageDialog(null, "Fel datumformat, vänligen ange ett nytt datum enligt 'YYYY-MM-DD'");
                txtRegDatum.setText("");
            }
        } else {
            JOptionPane.showMessageDialog(null, "Vänligen skriv ett annat datum!");
            txtRegDatum.setText("");
        }
        }
    }//GEN-LAST:event_btnAndraRegDatumActionPerformed

    private void btnAndraLosenordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAndraLosenordActionPerformed
        
        String nyttLosenord = txtLosenord.getText();
        String gammaltLosenord = lblLosen.getText();
        boolean losenFinns = Validering.stringFinns(nyttLosenord, gammaltLosenord);
        boolean textRutaArTom = Validering.textRutaArTom(nyttLosenord);

        if (textRutaArTom == false)
        {
        
        if (losenFinns == false) {

            try {
                String fraga = "Update Alien set losenord = '" + nyttLosenord + "' where namn = '" + nuvarandeUtomjording + "'";
                String svar = idb.fetchSingle(fraga);
                JOptionPane.showMessageDialog(null, "Lösenordet har ändrats!");
                txtLosenord.setText("");
                showInfo(nuvarandeUtomjording);
            } catch (InfException ex) {
                JOptionPane.showMessageDialog(null, "Det nya lösenordet är för långt, vänligen skriv ett nytt med max 6 tecken!");
                txtLosenord.setText("");
            }
        } else {
            JOptionPane.showMessageDialog(null, "Lösenordet har inte ändrats, Vänligen skriv in ett annat löseord!");
            txtLosenord.setText("");
        } 
        }
    }//GEN-LAST:event_btnAndraLosenordActionPerformed

    private void btnAndraTelefonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAndraTelefonActionPerformed
        
        String nyttTelefonNummer = txtTelefon.getText();
        String gammaltTelefonNummer = lblTelefon.getText();
        boolean TelefonFinns = Validering.stringFinns(nyttTelefonNummer, gammaltTelefonNummer);
        boolean textRutaArTom = Validering.textRutaArTom(nyttTelefonNummer);
        
        if (textRutaArTom == false)
        
        {
        if (TelefonFinns == false) {

            try {
                String fraga = "Update Alien set telefon = '" + nyttTelefonNummer + "' where namn = '" + nuvarandeUtomjording + "'";
                String svar = idb.fetchSingle(fraga);
                JOptionPane.showMessageDialog(null, "Telefonnumret har ändrats!");
                txtTelefon.setText("");
                showInfo(nuvarandeUtomjording);
            } catch (InfException ex) {
                JOptionPane.showMessageDialog(null, "Något har gått fel, vänligen prova igen.");
                txtTelefon.setText("");
            }
        } else {
            JOptionPane.showMessageDialog(null, "Telefonnumret har inte ändrats, Vänligen skriv in ett annat nummer!");
            txtTelefon.setText("");
        }  
        
        } 
    
          
    }//GEN-LAST:event_btnAndraTelefonActionPerformed

    private void btnAndraPlatsActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAndraPlatsActionPerformed
        
        String nyPlats = txtPlats.getText();
        String gammalPlats = lblPlats.getText();
        boolean platsFinns = Validering.stringFinns(nyPlats, gammalPlats);
        boolean textRutaArTom = Validering.textRutaArTom(nyPlats);

        if (textRutaArTom == false) {

            if (platsFinns == false) {

                try {
                    String fraga = "Select benamning from omrade where omrades_id = (Select Plats from alien where namn = '" + nuvarandeUtomjording + "')";
                    String svar = idb.fetchSingle(fraga);

                    String fraga1 = "select plats_ID from plats where Benamning = '" + nyPlats + "'";
                    String svar1 = idb.fetchSingle(fraga1);

                    if (svar1 != null) {
                        String fraga2 = "update alien set plats = '" + svar1 + "' where namn = '" + nuvarandeUtomjording + "'";
                        String svar2 = idb.fetchSingle(fraga2);
                        JOptionPane.showMessageDialog(null, "Platsen har ändrats!");
                        txtPlats.setText("");
                        showInfo(nuvarandeUtomjording);
                    } else {
                        JOptionPane.showMessageDialog(null, "Det finns ingen plats med namnet " + nyPlats + "! Vänligen skriv in en annan plats!");
                        txtPlats.setText("");
                    }
                } catch (InfException ex) {
                    JOptionPane.showMessageDialog(null, "Något har gått fel, vänligen prova igen.");
                    txtPlats.setText("");
                }
            } else {
                JOptionPane.showMessageDialog(null, "Den nya platsen är samma som den gamla. Vänligen skriv en ny plats!");
                txtPlats.setText("");
            }

        }     
    }//GEN-LAST:event_btnAndraPlatsActionPerformed

    private void btnAndraRasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAndraRasActionPerformed
        
        String boglodite = "boglodite";
        String squid = "squid";
        String worm = "worm";
        
        String nyRas = txtRas.getText().toLowerCase();
        String gammalRas = lblRas.getText();
        boolean rasAnvands = Validering.stringFinns(nyRas, gammalRas);
        boolean textRutaArTom = Validering.textRutaArTom(nyRas);
        String alienID = visaInfoOmAlien.visaID(nuvarandeUtomjording);
        System.out.println(alienID);
        System.out.println(nyRas);
        System.out.println(gammalRas);
        
        if (textRutaArTom == false)
        {
        
        if (rasAnvands == false )
        {
        try {
        if (nyRas.equals(boglodite))
        {
            
            String fraga1 = "insert into boglodite values (" + alienID + ", 2)";
            idb.fetchSingle(fraga1);
            String fraga2 = "delete from " + gammalRas + " where alien_id = " + alienID;
            idb.fetchSingle(fraga2);
            System.out.println(fraga1);
            System.out.println(fraga2);
            JOptionPane.showMessageDialog(null, "Rasen har ändrats!");
            setInfo(nuvarandeUtomjording);
            txtRas.setText("");
        }
        else if (nyRas.equals(worm))
        {
            String fraga1 = "insert into worm values (" + alienID + ")";
            idb.fetchSingle(fraga1);
            String fraga2 = "delete from " + gammalRas + " where alien_id = " + alienID;
            idb.fetchSingle(fraga2);
            System.out.println(fraga1);
            System.out.println(fraga2);
            JOptionPane.showMessageDialog(null, "Rasen har ändrats!");
            setInfo(nuvarandeUtomjording);
            txtRas.setText("");
        }
        else if (nyRas.equals(squid))
        {
            String fraga1 = "insert into squid values (" + alienID + ", 4)";
            idb.fetchSingle(fraga1);
            String fraga2 = "delete from " + gammalRas + " where alien_id = " + alienID;
            idb.fetchSingle(fraga2);
            JOptionPane.showMessageDialog(null, "Rasen har ändrats!");
            setInfo(nuvarandeUtomjording);
            txtRas.setText("");
        }
        else
        {
            JOptionPane.showMessageDialog(null, "Det finns ingen ras med namnet " + nyRas + "!");
            txtRas.setText("");
        }
        }
         catch (InfException ex) {
                    JOptionPane.showMessageDialog(null, "Något har gått fel, vänligen prova igen.");
                    System.out.println(ex);
                    txtRas.setText("");
                }
        }
        else
        {
            JOptionPane.showMessageDialog(null, "Den nya rasen är samma som den nuvarande, vänligen skriv en annan ras!");
            txtRas.setText("");
        }
        
        }
        
        
    }//GEN-LAST:event_btnAndraRasActionPerformed

    private void btnAndraAnsvarigAgentActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAndraAnsvarigAgentActionPerformed
        
        String nyAnsvarigAgent = txtAnsvarigAgent.getText();
        String gammalAnsvarigAgent = lblAnsvarigAgent.getText();
        boolean agentAnvands = Validering.stringFinns(nyAnsvarigAgent, gammalAnsvarigAgent);
        boolean textRutaArTom = Validering.textRutaArTom(nyAnsvarigAgent);
        boolean agentFinns = false;

        if (textRutaArTom == false) {

            if (agentAnvands == false) {

                try {
                    String fraga = "Select namn from agent";
                    ArrayList<String> agentNamnlista = idb.fetchColumn(fraga);

                    for (String agentNamn : agentNamnlista)
                    {
                        if (agentNamn.toLowerCase().equals(nyAnsvarigAgent.toLowerCase()))
                        {
                            agentFinns = true;
                            break;
                        }
                    }

                    if (agentFinns == true) {
                        String fraga1 = "select agent_id from agent where namn = '" + nyAnsvarigAgent + "'";
                        String svar1 = idb.fetchSingle(fraga1);
                        String fraga2 = "update alien set ansvarig_Agent = '" + svar1 + "' where namn = '" + nuvarandeUtomjording + "'";
                        String svar2 = idb.fetchSingle(fraga2);
                        JOptionPane.showMessageDialog(null, "Ansvarig agent har ändrats!");
                        txtAnsvarigAgent.setText("");
                        setInfo(nuvarandeUtomjording);
                    } else {
                        JOptionPane.showMessageDialog(null, "Det finns ingen agent med namnet " + nyAnsvarigAgent + "! Vänligen skriv in en annan agent!");
                        txtAnsvarigAgent.setText("");
                    }
                } catch (InfException ex) {
                    JOptionPane.showMessageDialog(null, "Något har gått fel, vänligen prova igen.");
                    txtAnsvarigAgent.setText("");
                }
            } else {
                JOptionPane.showMessageDialog(null, "Den nya agenten är samma som den gamla. Vänligen skriv en ny agent!");
                txtAnsvarigAgent.setText("");
            }

        }   
        
    }//GEN-LAST:event_btnAndraAnsvarigAgentActionPerformed

    private void txtLosenordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtLosenordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtLosenordActionPerformed

    public void setNuvarandeAgent (String nuvarandeAgent)
    {
        this.nuvarandeAgent = nuvarandeAgent;
    }
    
    public void setNuvarandeUtomjording (String utomjording)
    {
        nuvarandeUtomjording = utomjording;
    }
    
    public String visaNuvarandeUtomjording()
    {
        return nuvarandeUtomjording;
    }
    
    public void showInfo (String namn)
    {
        try {
       String fraga1 = "SELECT namn FROM alien where namn = '" + namn + "'";
       //String fraga2 = "Select telefon from alien where namn = '" + namn + "'";
       String fraga3 = "Select Registreringsdatum from alien where namn = '" + namn + "'";
       String fraga4 = "Select benamning from plats where plats_id = (Select Plats from alien where namn = '" + namn + "')";
       String fraga5 = "Select telefon from alien where namn = '" + namn + "'";
       String fraga6 = "Select losenord from alien where namn = '" + namn + "'";
       String fraga7 = "Select alien_id from alien where namn = '" + namn + "'";
        
       String svar1 = idb.fetchSingle(fraga1);
       //String svar2 = idb.fetchSingle(fraga2);
       String svar3 = idb.fetchSingle(fraga3);
       String svar4 = idb.fetchSingle(fraga4);
       String svar5 = idb.fetchSingle(fraga5);
       String svar6 = idb.fetchSingle(fraga6);
       String svar7 = idb.fetchSingle(fraga7);
       
       lblNamn.setText(svar1);
       lblRas.setText(visaInfoOmAlien.visaRas(namn));
       lblRegDatum.setText(svar3);
       lblPlats.setText(svar4);
       lblTelefon.setText(svar5);
       lblLosen.setText(svar6);
       lblID.setText(svar7);
       
        }
        catch (InfException ex) {
            Logger.getLogger(InloggningsTyp.class.getName()).log(Level.SEVERE, null, ex);
            System.out.println("Ett fel har uppstått " + ex);
        }
    }
    
    public void setInfo (String namn)
    {
       lblNamn.setText(visaInfoOmAlien.visaNamn(namn));
       lblRas.setText(visaInfoOmAlien.visaRas(namn));
       lblRegDatum.setText(visaInfoOmAlien.visaRegDatum(namn));
       lblPlats.setText(visaInfoOmAlien.visaPlats(namn));
       lblTelefon.setText(visaInfoOmAlien.visaTelefon(namn));
       lblLosen.setText(visaInfoOmAlien.visaLosenord(namn));
       lblID.setText(visaInfoOmAlien.visaID(namn));
       lblAnsvarigAgent.setText(visaInfoOmAlien.visaAnsvarigAgent(namn));
    }
    
    public boolean kollaNamn(String namn)
    {
        boolean namnetFinns = false;

        try {
            String fraga = "Select namn from alien";
            ArrayList<String> alienNamnlista = idb.fetchColumn(fraga);

            for (String alienNamn : alienNamnlista) {
                if (alienNamn.toLowerCase().equals(namn.toLowerCase())) {
                    namnetFinns = true;
                    break;
                }
            }

        } catch (InfException ex) {
            Logger.getLogger(InloggningsTyp.class.getName()).log(Level.SEVERE, null, ex);
            System.out.println("Ett fel har uppstått " + ex);
        }
        return namnetFinns;
    }
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel HuvudText;
    private javax.swing.JButton btnAndraAnsvarigAgent;
    private javax.swing.JButton btnAndraLosenord;
    private javax.swing.JButton btnAndraNamn;
    private javax.swing.JButton btnAndraPlats;
    private javax.swing.JButton btnAndraRas;
    private javax.swing.JButton btnAndraRegDatum;
    private javax.swing.JButton btnAndraTelefon;
    private javax.swing.JButton btnTillbaka;
    private javax.swing.JButton btnTillbakaTillHM;
    private javax.swing.JLabel iblAnsvarigAgentRubrik;
    private javax.swing.JLabel lblAnsvarigAgent;
    private javax.swing.JLabel lblID;
    private javax.swing.JLabel lblIdNummerRubrik;
    private javax.swing.JLabel lblInfoRubrik;
    private javax.swing.JLabel lblLosen;
    private javax.swing.JLabel lblLosenordRubrik;
    private javax.swing.JLabel lblNamn;
    private javax.swing.JLabel lblNamnRubrik;
    private javax.swing.JLabel lblPlats;
    private javax.swing.JLabel lblPlatsRubrik;
    private javax.swing.JLabel lblRas;
    private javax.swing.JLabel lblRasRubrik;
    private javax.swing.JLabel lblRegDatum;
    private javax.swing.JLabel lblRegDatumRubrik;
    private javax.swing.JLabel lblTelefon;
    private javax.swing.JLabel lblTelefonRubrik;
    private javax.swing.JTextField txtAnsvarigAgent;
    private javax.swing.JTextField txtLosenord;
    private javax.swing.JTextField txtNamn;
    private javax.swing.JTextField txtPlats;
    private javax.swing.JTextField txtRas;
    private javax.swing.JTextField txtRegDatum;
    private javax.swing.JTextField txtTelefon;
    // End of variables declaration//GEN-END:variables
}
