/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package MibG12;

import javax.swing.JOptionPane;
import oru.inf.InfDB;
import oru.inf.InfException;

/**
 *
 * @author eriknilsson
 */
public class AndraLosenAlien extends javax.swing.JFrame {
    private static InfDB idb;
    private String nuvarandeUtomjording;
    /**
     * Creates new form AndraLosenAlien
     */
    public AndraLosenAlien(InfDB idb) {
        initComponents();
        this.idb = idb;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblGammaltLosen1 = new javax.swing.JLabel();
        lblGammaltLosen2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        gammaltLosenord1 = new javax.swing.JPasswordField();
        gammaltLosenord2 = new javax.swing.JPasswordField();
        nyttLosenord = new javax.swing.JPasswordField();
        btnTillbaka = new javax.swing.JButton();
        btnAndraLosen = new javax.swing.JButton();
        lblStatus = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblGammaltLosen1.setText("Nuvarande lösen");

        lblGammaltLosen2.setText("Nuvarande lösen");

        jLabel3.setText("Nytt lösen");

        nyttLosenord.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nyttLosenordActionPerformed(evt);
            }
        });

        btnTillbaka.setText("TIllbaka");
        btnTillbaka.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTillbakaActionPerformed(evt);
            }
        });

        btnAndraLosen.setText("Ändra lösen");
        btnAndraLosen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAndraLosenActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblGammaltLosen1)
                            .addComponent(lblGammaltLosen2, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addGap(12, 12, 12)
                                .addComponent(jLabel3)))
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(btnAndraLosen)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnTillbaka)
                        .addGap(83, 83, 83))))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(12, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(gammaltLosenord2, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(gammaltLosenord1, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(nyttLosenord, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 131, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(257, 257, 257))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addComponent(lblStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 159, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(37, 37, 37))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(36, 36, 36)
                .addComponent(lblGammaltLosen1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(gammaltLosenord1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblGammaltLosen2)
                .addGap(8, 8, 8)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(gammaltLosenord2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 18, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(nyttLosenord, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 41, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnTillbaka)
                    .addComponent(btnAndraLosen))
                .addGap(29, 29, 29))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void nyttLosenordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nyttLosenordActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nyttLosenordActionPerformed

    private void btnTillbakaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTillbakaActionPerformed
       HuvudMenyUtomjording hMU = new HuvudMenyUtomjording (idb, nuvarandeUtomjording);
       hMU.setVisible(true);
       hMU.setValkommenUtomjording();
       dispose();
    }//GEN-LAST:event_btnTillbakaActionPerformed

    private void btnAndraLosenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAndraLosenActionPerformed
        // TODO add your handling code here:
        

        boolean gammaltLosenKorrekt = losenordKorrekt();

        if (gammaltLosenKorrekt == true) 
        {
            if (nyttLosenord != gammaltLosenord2) 
            {
                char[] c = nyttLosenord.getPassword();
                String nyttLosen = new String(c);
                boolean losenordForLangt = Validering.kollaLosenordsLangd(nyttLosen);

                if (losenordForLangt == false) 
                {
                    
                    setLosenord(nyttLosen);
                    gammaltLosenord1.setText("");
                    gammaltLosenord2.setText("");
                    nyttLosenord.setText("");
                } 
                else 
                {
                    JOptionPane.showMessageDialog(null, "Lösenordet är samma som det tidigate, vänligen välj ett annat lösenord!");
                    gammaltLosenord1.setText("");
                    gammaltLosenord2.setText("");
                    nyttLosenord.setText("");
                }
            } else {
                JOptionPane.showMessageDialog(null, "Gamla lösenordet är fel, vänligen prova igen!");
                gammaltLosenord1.setText("");
                gammaltLosenord2.setText("");
                nyttLosenord.setText("");
            }
        }
            
     
    }//GEN-LAST:event_btnAndraLosenActionPerformed
    public void setNuvarandeUtomjording(String namn){
        nuvarandeUtomjording = namn;
    }
    
    public boolean losenordKorrekt()
    {
        boolean losenordKorrekt = false;
        
        char[] c1 = gammaltLosenord1.getPassword();
        String losen1 = new String (c1);
        
        char[] c2 = gammaltLosenord2.getPassword();
        String losen2 = new String (c2);
        
        if (losen1.equals(losen2))
        {
            lblStatus.setText("Lösenord korrekt");
            losenordKorrekt = true;
        }
        else {
            lblStatus.setText("Fel Lösenord");
            System.out.println(losen1);
            System.out.println(losen2);
        }
        
        return losenordKorrekt;
    }
    
    public boolean setLosenord (String losenord)
    {
        boolean losenAndrat = false;
        
        try {
            System.out.println(nuvarandeUtomjording);
            String fraga = "UPDATE Alien set Losenord = '" + losenord + "' where Namn = '" + nuvarandeUtomjording + "'";
            idb.fetchSingle(fraga);
            JOptionPane.showMessageDialog(null, "Lösenordet har ändrats!");
            losenAndrat = true;
        }
        catch (InfException ex) {
            JOptionPane.showMessageDialog(null, "Lösenordet får max vara 6 tecken!");
            System.out.println(ex + " har inträffat!");
        }
        return losenAndrat;
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(AndraLosenAlien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(AndraLosenAlien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(AndraLosenAlien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(AndraLosenAlien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new AndraLosenAlien(idb).setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAndraLosen;
    private javax.swing.JButton btnTillbaka;
    private javax.swing.JPasswordField gammaltLosenord1;
    private javax.swing.JPasswordField gammaltLosenord2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel lblGammaltLosen1;
    private javax.swing.JLabel lblGammaltLosen2;
    private javax.swing.JLabel lblStatus;
    private javax.swing.JPasswordField nyttLosenord;
    // End of variables declaration//GEN-END:variables
}
