/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package MibG12;

import javax.swing.JOptionPane;
import oru.inf.InfDB;
import oru.inf.InfException;

/**
 * Klass för huvudmeny dit utomjordingar kommer när de har loggat in
 * @author 
 */
public class HuvudMenyUtomjording extends javax.swing.JFrame {
        private static InfDB idb;
        private String nuvarandeUtomjording;
    /**
     * Konstruktor för HuvudMenyUtomjording
     */
    public HuvudMenyUtomjording(InfDB idb, String nuvarandeUtomjording) {
        initComponents();
        this.idb = idb;
        this.nuvarandeUtomjording = nuvarandeUtomjording;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblValkommen = new javax.swing.JLabel();
        btnAndraLosen = new javax.swing.JButton();
        btnVisaChef = new javax.swing.JButton();
        lblVisaChef = new javax.swing.JLabel();
        btnLoggaUt = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblValkommen.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblValkommen.setText("jLabel1");

        btnAndraLosen.setText("Ändra mitt lösenord");
        btnAndraLosen.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAndraLosenActionPerformed(evt);
            }
        });

        btnVisaChef.setText("Visa områdeschef över mitt område");
        btnVisaChef.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVisaChefActionPerformed(evt);
            }
        });

        lblVisaChef.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);

        btnLoggaUt.setText("Logga Ut");
        btnLoggaUt.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoggaUtActionPerformed(evt);
            }
        });

        jLabel1.setText("Välj någon utav de operationer du vill utföra");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(128, 128, 128)
                .addComponent(lblValkommen, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(lblVisaChef, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(106, 106, 106))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(49, 49, 49)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(btnLoggaUt, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnAndraLosen, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(btnVisaChef, javax.swing.GroupLayout.DEFAULT_SIZE, 305, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(73, 73, 73)
                        .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 265, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(53, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lblValkommen)
                .addGap(36, 36, 36)
                .addComponent(jLabel1)
                .addGap(33, 33, 33)
                .addComponent(btnAndraLosen)
                .addGap(26, 26, 26)
                .addComponent(btnVisaChef)
                .addGap(26, 26, 26)
                .addComponent(btnLoggaUt)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 43, Short.MAX_VALUE)
                .addComponent(lblVisaChef, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents
// Metod för att logga ut från HuvudMenyUtomjording och komma till InloggningsTyp
    private void btnLoggaUtActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoggaUtActionPerformed
        InloggningsTyp iT = new InloggningsTyp(idb);
        iT.setVisible(true);
        dispose();

    }//GEN-LAST:event_btnLoggaUtActionPerformed
// Metod som formar välkomstmeddelande för vilken utomjording som loggat in    
    public void setValkommenUtomjording()
    {
        
        lblValkommen.setText("Välkommen " + Validering.storForstaBokstav(nuvarandeUtomjording) +"!");
    
    
}
// Metod som sätter vilken utomjording som har loggat in
    public void setNuvarandeUtomjording(String namn){
        nuvarandeUtomjording = namn;
    }
//Metod som visar vem områdeschefen är för det område som den nuvarande utomjordingen befinner sig i    
    private void btnVisaChefActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVisaChefActionPerformed
        // TODO add your handling code here:
        
        try {
            String fraga = "select Namn from Agent where Agent_ID=(select Agent_ID from Omradeschef where Omradeschef.Omrade =(select Omrades_ID from Omrade where Omrades_ID=(select finns_i from plats where plats_id=(select Plats from Alien where Alien.Namn='" + nuvarandeUtomjording + "'))))";
            String svar = idb.fetchSingle(fraga);

            if (svar == null) {
                JOptionPane.showMessageDialog(null, "Denna utomjording sområde har för tillfället ingen områdeschef.");
            } else {
                VisaInfoOmAgent aI = new VisaInfoOmAgent(idb, svar, false, nuvarandeUtomjording, true);
                aI.setVisible(true);
                aI.setInfo(svar);
                aI.setNuvarandeUtomjording(nuvarandeUtomjording);
                dispose();
            }
        }
      catch(InfException e){
          JOptionPane.showMessageDialog(null, "Något gick fel");
          System.out.println(e);
      }
    }//GEN-LAST:event_btnVisaChefActionPerformed
// Metod som öppnar Andra Lösenords fönsret då man trycker på knappen
    private void btnAndraLosenActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAndraLosenActionPerformed
        
        AndraLosenord aLA = new AndraLosenord(idb, true);
        aLA.setVisible(true);
        aLA.setNuvarandeUtomjording(nuvarandeUtomjording);
        dispose();
    }//GEN-LAST:event_btnAndraLosenActionPerformed

    
      


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAndraLosen;
    private javax.swing.JButton btnLoggaUt;
    private javax.swing.JButton btnVisaChef;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel lblValkommen;
    private javax.swing.JLabel lblVisaChef;
    // End of variables declaration//GEN-END:variables
}
