/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package MibG12;

import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import oru.inf.InfDB;
import oru.inf.InfException;

/**
 *
 * @author Victo
 */
public class VisaInfoOmAgent extends javax.swing.JFrame {

  private static InfDB idb;
  private String nuvarandeAgent;
  private String nuvarandeUtomjording;
  //private HuvudMenyAgent huvudMenyAdmin; 
  //private HuvudMenyUtomjording huvudMenyUtomjording;
  private boolean anvandareArAdmin;
    
    /**
     * Creates new form AgentInfo
     */
    public VisaInfoOmAgent(InfDB idb) {
        initComponents();
        this.idb = idb;
        anvandareArAdmin = false;
        btnTillbakaTillHuvudMeny.setVisible(false);
        
    }

    VisaInfoOmAgent(MibG12.Startklass idb) {
        throw new UnsupportedOperationException("Not supported yet."); // Generated from nbfs://nbhost/SystemFileSystem/Templates/Classes/Code/GeneratedMethodBody
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblBetackningRubrik = new javax.swing.JLabel();
        lblTelefonRubrik = new javax.swing.JLabel();
        lblAdminstatusRubrik = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        lblAnstallningsDatumRubrik = new javax.swing.JLabel();
        lblOmradeRubrik = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        lblAgentNamn = new javax.swing.JLabel();
        lblAgentTelefon = new javax.swing.JLabel();
        lblAdminStatus = new javax.swing.JLabel();
        lblAnstallningsDatum = new javax.swing.JLabel();
        lblOmrade = new javax.swing.JLabel();
        lblIdNummerKol = new javax.swing.JLabel();
        lblIdNummer = new javax.swing.JLabel();
        btnTillbakaTillHuvudMeny = new javax.swing.JButton();
        lblLosenordRubrik = new javax.swing.JLabel();
        lblLosenord = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblBetackningRubrik.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblBetackningRubrik.setText("Betäckning:");

        lblTelefonRubrik.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblTelefonRubrik.setText("Telefon:");

        lblAdminstatusRubrik.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblAdminstatusRubrik.setText("Adminstatus:");

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel4.setText("Agent information");

        lblAnstallningsDatumRubrik.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblAnstallningsDatumRubrik.setText("Anställningsdatum:");

        lblOmradeRubrik.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblOmradeRubrik.setText("Område:");

        jButton1.setText("Tillbaka");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        lblAgentNamn.setText("Namn");

        lblAgentTelefon.setText("Telefonummer");

        lblAdminStatus.setText("Adminstatus");

        lblAnstallningsDatum.setText("Anställningsdatum");

        lblOmrade.setText("Område");

        lblIdNummerKol.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblIdNummerKol.setText("ID-Nummer:");

        lblIdNummer.setText("ID");

        btnTillbakaTillHuvudMeny.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        btnTillbakaTillHuvudMeny.setText("Tillbaka till huvudmeny");
        btnTillbakaTillHuvudMeny.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTillbakaTillHuvudMenyActionPerformed(evt);
            }
        });

        lblLosenordRubrik.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblLosenordRubrik.setText("Lösenord:");

        lblLosenord.setText("hej");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(130, 130, 130)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblAnstallningsDatumRubrik, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblOmradeRubrik, javax.swing.GroupLayout.PREFERRED_SIZE, 85, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblIdNummerKol, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblBetackningRubrik, javax.swing.GroupLayout.PREFERRED_SIZE, 71, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblTelefonRubrik, javax.swing.GroupLayout.PREFERRED_SIZE, 53, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblAdminstatusRubrik, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblLosenordRubrik, javax.swing.GroupLayout.PREFERRED_SIZE, 94, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblIdNummer, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblOmrade, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblAnstallningsDatum, javax.swing.GroupLayout.PREFERRED_SIZE, 75, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblAgentNamn, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblAdminStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblAgentTelefon, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblLosenord, javax.swing.GroupLayout.PREFERRED_SIZE, 93, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 221, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(53, 53, 53)
                        .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(72, 72, 72)
                        .addComponent(btnTillbakaTillHuvudMeny)))
                .addContainerGap(54, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(jLabel4)
                .addGap(30, 30, 30)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblAdminstatusRubrik)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblAgentNamn)
                                .addGap(18, 18, 18)
                                .addComponent(lblAgentTelefon)
                                .addGap(18, 18, 18)
                                .addComponent(lblAdminStatus, javax.swing.GroupLayout.PREFERRED_SIZE, 16, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblAnstallningsDatumRubrik)
                            .addComponent(lblAnstallningsDatum)))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(lblBetackningRubrik)
                        .addGap(18, 18, 18)
                        .addComponent(lblTelefonRubrik)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblOmradeRubrik)
                    .addComponent(lblOmrade))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblIdNummerKol)
                    .addComponent(lblIdNummer))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblLosenordRubrik)
                    .addComponent(lblLosenord))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 30, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnTillbakaTillHuvudMeny, javax.swing.GroupLayout.PREFERRED_SIZE, 41, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    public void anvandareArAdmin()
    {
        anvandareArAdmin = true;
        btnTillbakaTillHuvudMeny.setVisible(true);
    }
    
    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        if (anvandareArAdmin == true)
        {
            ValjAgentFromAdmin valjAgentFromAdmin = new ValjAgentFromAdmin(idb, nuvarandeAgent);
            valjAgentFromAdmin.setVisible(true);
            dispose();
        }
        
        else if (anvandareArAdmin == false)
        {
            HuvudMenyUtomjording hMU = new HuvudMenyUtomjording(idb, nuvarandeUtomjording);
            hMU.setNuvarandeUtomjording(nuvarandeUtomjording);
            hMU.setVisible(true);
            hMU.setValkommenUtomjording();
            dispose();
        }
    }//GEN-LAST:event_jButton1ActionPerformed

    private void btnTillbakaTillHuvudMenyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTillbakaTillHuvudMenyActionPerformed
        HuvudMenyAdmin hMA = new HuvudMenyAdmin (idb, nuvarandeAgent);
        hMA.setVisible(true);
        dispose();
    }//GEN-LAST:event_btnTillbakaTillHuvudMenyActionPerformed

    public void setNuvarandeAgent (String nuvarandeAgent)
    {
        this.nuvarandeAgent = nuvarandeAgent;
    }
    
    public void setNuvarandeUtomjording (String nuvarandeUtomjording)
    {
        this.nuvarandeUtomjording = nuvarandeUtomjording;
    }
    
    public void setInfo(String namn)
    {
       lblAgentNamn.setText(visaAgentNamn(namn));
       lblAgentTelefon.setText(visaAgentTelefon(namn));
       lblAdminStatus.setText(visaAgentAdminstatus(namn));
       lblAnstallningsDatum.setText(visaAgentAnstallningsDatum(namn));
       lblOmrade.setText(visaAgentOmrade(namn));
       lblIdNummer.setText(visaAgentID(namn));
       lblLosenord.setText(visaAgentLosenord(namn));
    }
    
    public String visaAgentNamn (String namn)
    {
        String namnet = "";
        
        try {
        
        String fraga1 = "Select namn from agent where namn = '" + namn + "'";
        String svar1 = idb.fetchSingle(fraga1);
        namnet = svar1;
        }
        
        catch (InfException ex) {
            System.out.println("Ett fel har uppstått " + ex);
        }
        
        return namnet;
    }
    
    public String visaAgentTelefon (String namn)
    {
        String nummer = "0";
        
        try {
        
        String fraga1 = "Select telefon from agent where namn = '" + namn + "'";
        String svar1 = idb.fetchSingle(fraga1);
        nummer = svar1;
        }
        
        catch (InfException ex) {
            System.out.println("Ett fel har uppstått " + ex);
        }
        
        return nummer;
    }
    
    public String visaAgentAdminstatus (String namn)
    {
        String admin = "";
        
        try {
        
        String fraga1 = "Select administrator from agent where namn = '" + namn + "'";
        String svar1 = idb.fetchSingle(fraga1);
        admin = svar1;
        }
        
        catch (InfException ex) {
            System.out.println("Ett fel har uppstått " + ex);
        }
        
        String adminSvar = Validering.setAdminStatus(admin);
        return adminSvar;
    }
    
    public String visaAgentAnstallningsDatum (String namn)
    {
        String datum = "";
        
        try {
        
        String fraga1 = "Select anstallningsdatum from agent where namn = '" + namn + "'";
        String svar1 = idb.fetchSingle(fraga1);
        datum = svar1;
        }
        
        catch (InfException ex) {
            System.out.println("Ett fel har uppstått " + ex);
        }
        
        return datum;
    }
    
    public String visaAgentOmrade (String namn)
    {
        String omrade = "";
        
        try {
        
        String fraga1 = "Select benamning from omrade where Omrades_ID = (Select omrade from agent where namn = '" + namn + "')";
        String svar1 = idb.fetchSingle(fraga1);
        omrade = svar1;
        }
        
        catch (InfException ex) {
            System.out.println("Ett fel har uppstått " + ex);
        }
        
        return omrade;
    }
    
     public String visaAgentID (String namn)
    {
        String id = "";
        
        try {
        
        String fraga1 = "Select agent_id from agent where namn = '" + namn + "'";
        String svar1 = idb.fetchSingle(fraga1);
        id = svar1;
        }
        
        catch (InfException ex) {
            System.out.println("Ett fel har uppstått " + ex);
        }
        
        return id;
    }
     
     public String visaAgentLosenord (String namn)
    {
        String losenord = "";
        
        try {
        
        String fraga1 = "Select losenord from agent where namn = '" + namn + "'";
        String svar1 = idb.fetchSingle(fraga1);
        losenord = svar1;
        }
        
        catch (InfException ex) {
            System.out.println("Ett fel har uppstått " + ex);
        }
        
        return losenord;
    }
    
    
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnTillbakaTillHuvudMeny;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel lblAdminStatus;
    private javax.swing.JLabel lblAdminstatusRubrik;
    private javax.swing.JLabel lblAgentNamn;
    private javax.swing.JLabel lblAgentTelefon;
    private javax.swing.JLabel lblAnstallningsDatum;
    private javax.swing.JLabel lblAnstallningsDatumRubrik;
    private javax.swing.JLabel lblBetackningRubrik;
    private javax.swing.JLabel lblIdNummer;
    private javax.swing.JLabel lblIdNummerKol;
    private javax.swing.JLabel lblLosenord;
    private javax.swing.JLabel lblLosenordRubrik;
    private javax.swing.JLabel lblOmrade;
    private javax.swing.JLabel lblOmradeRubrik;
    private javax.swing.JLabel lblTelefonRubrik;
    // End of variables declaration//GEN-END:variables
}
