/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package MibG12;

import java.util.ArrayList;
import oru.inf.InfException;
import java.util.logging.Level;
import java.util.logging.Logger;
import oru.inf.InfException;
import oru.inf.InfDB;

/**
 *
 * @author Victo
 */
public class VisaInfoOmAlien extends javax.swing.JFrame {

    InfDB idb;
    private String nuvarandeAgent;
    private String nuvarandeUtomjording;
    
    public VisaInfoOmAlien(InfDB idb, String nuvarandeAgent) {
        initComponents();
        this.idb = idb;
        this.nuvarandeAgent = nuvarandeAgent;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblHuvudText = new javax.swing.JLabel();
        lblNamnRubrik = new javax.swing.JLabel();
        lblRasRubrik = new javax.swing.JLabel();
        lblRegistreringsDatumRubrik = new javax.swing.JLabel();
        lblPlatsRubrik = new javax.swing.JLabel();
        lblTelefonRubrik = new javax.swing.JLabel();
        lblLosenordRubrik = new javax.swing.JLabel();
        lblIDRubrik = new javax.swing.JLabel();
        lblNamn = new javax.swing.JLabel();
        lblRas = new javax.swing.JLabel();
        lblRegDatum = new javax.swing.JLabel();
        lblPlats = new javax.swing.JLabel();
        lblTelefon = new javax.swing.JLabel();
        lblLosenord = new javax.swing.JLabel();
        lblID = new javax.swing.JLabel();
        btnTillbaka = new javax.swing.JButton();
        btnTillbakaTillHuvudmeny = new javax.swing.JButton();
        lblAnsvarigAgentRubrik = new javax.swing.JLabel();
        lblAnsvarigAgent = new javax.swing.JLabel();
        lblRasExtraRubrik = new javax.swing.JLabel();
        lblRasExtra = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        lblHuvudText.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        lblHuvudText.setText("Information om Utomjording");

        lblNamnRubrik.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblNamnRubrik.setText("Namn: ");

        lblRasRubrik.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblRasRubrik.setText("Ras:");

        lblRegistreringsDatumRubrik.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblRegistreringsDatumRubrik.setText("Registreringsdatum:");

        lblPlatsRubrik.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblPlatsRubrik.setText("Plats:");

        lblTelefonRubrik.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblTelefonRubrik.setText("Telefon:");

        lblLosenordRubrik.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblLosenordRubrik.setText("Lösenord:");

        lblIDRubrik.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblIDRubrik.setText("ID-nummer:");

        lblNamn.setText("Namn");

        lblRas.setText("Ras");

        lblRegDatum.setText("RegDatum");

        lblPlats.setText("Plats");

        lblTelefon.setText("Telefon");

        lblLosenord.setText("HejHej");

        lblID.setText("ID");

        btnTillbaka.setText("Tillbaka");
        btnTillbaka.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTillbakaActionPerformed(evt);
            }
        });

        btnTillbakaTillHuvudmeny.setFont(new java.awt.Font("Segoe UI", 0, 10)); // NOI18N
        btnTillbakaTillHuvudmeny.setText("Tillbaka Till Huvudmeny");
        btnTillbakaTillHuvudmeny.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnTillbakaTillHuvudmenyActionPerformed(evt);
            }
        });

        lblAnsvarigAgentRubrik.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblAnsvarigAgentRubrik.setText("Ansvarig agent:");

        lblAnsvarigAgent.setText("ID");

        lblRasExtraRubrik.setFont(new java.awt.Font("Segoe UI", 1, 12)); // NOI18N
        lblRasExtraRubrik.setText("Antal Boogies:");

        lblRasExtra.setText("3");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(64, 64, 64)
                .addComponent(btnTillbaka, javax.swing.GroupLayout.PREFERRED_SIZE, 90, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnTillbakaTillHuvudmeny)
                .addGap(31, 31, 31))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblRegistreringsDatumRubrik, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(lblRegDatum, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblLosenordRubrik)
                                .addGap(18, 18, 18)
                                .addComponent(lblLosenord, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(lblRasRubrik)
                            .addComponent(lblNamnRubrik)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblTelefonRubrik)
                                    .addComponent(lblPlatsRubrik))
                                .addGap(27, 27, 27)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblPlats, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(lblTelefon, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addComponent(lblAnsvarigAgentRubrik)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(lblAnsvarigAgent, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                    .addComponent(lblIDRubrik)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(lblID, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(lblRasExtraRubrik, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(lblRasExtra, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(97, 97, 97)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lblNamn, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblRas, javax.swing.GroupLayout.PREFERRED_SIZE, 110, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(76, 76, 76)
                        .addComponent(lblHuvudText, javax.swing.GroupLayout.PREFERRED_SIZE, 258, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addContainerGap(66, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(lblHuvudText)
                .addGap(26, 26, 26)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNamnRubrik)
                    .addComponent(lblNamn))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblRasRubrik)
                    .addComponent(lblRas))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 18, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblRasExtraRubrik)
                    .addComponent(lblRasExtra))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblRegistreringsDatumRubrik)
                    .addComponent(lblRegDatum))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblPlatsRubrik)
                    .addComponent(lblPlats))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTelefonRubrik)
                    .addComponent(lblTelefon))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblLosenordRubrik)
                    .addComponent(lblLosenord))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblIDRubrik)
                    .addComponent(lblID))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblAnsvarigAgentRubrik)
                    .addComponent(lblAnsvarigAgent))
                .addGap(34, 34, 34)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnTillbakaTillHuvudmeny, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnTillbaka, javax.swing.GroupLayout.PREFERRED_SIZE, 34, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(21, 21, 21))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnTillbakaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTillbakaActionPerformed
        ValjAlienFromAgentHuvudMeny vAFAHM = new ValjAlienFromAgentHuvudMeny(idb, nuvarandeAgent);
        vAFAHM.setVisible(true);
        vAFAHM.visaBaraInfo();
        dispose();
    }//GEN-LAST:event_btnTillbakaActionPerformed

    private void btnTillbakaTillHuvudmenyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnTillbakaTillHuvudmenyActionPerformed
        HuvudMenyAgent hMA = new HuvudMenyAgent (idb, nuvarandeAgent);
        hMA.setHuvudText(nuvarandeAgent);
        hMA.setVisible(true);
        dispose();
    }//GEN-LAST:event_btnTillbakaTillHuvudmenyActionPerformed

    public void showInfo (String namn)
    {
        try {
       String fraga1 = "SELECT namn FROM alien where namn = '" + namn + "'";
       //String fraga2 = "Select benamning from omrade where omrades_id = (Select Plats from alien where namn = '" + namn + "')";
       String fraga3 = "Select Registreringsdatum from alien where namn = '" + namn + "'";
       String fraga4 = "Select benamning from plats where plats_id = (Select Plats from alien where namn = '" + namn + "')";
       String fraga5 = "Select telefon from alien where namn = '" + namn + "'";
       String fraga6 = "Select losenord from alien where namn = '" + namn + "'";
       String fraga7 = "Select alien_id from alien where namn = '" + namn + "'";
       String fraga8 = "Select namn from agent where agent_id = (Select Ansvarig_Agent from alien where namn = '" + namn + "')";
        
       String svar1 = idb.fetchSingle(fraga1);
       //String svar2 = idb.fetchSingle(fraga2);
       String svar2 = visaRas(namn);
       String svar3 = idb.fetchSingle(fraga3);
       String svar4 = idb.fetchSingle(fraga4);
       String svar5 = idb.fetchSingle(fraga5);
       String svar6 = idb.fetchSingle(fraga6);
       String svar7 = idb.fetchSingle(fraga7);
       String svar8 = idb.fetchSingle(fraga8);
       
       lblNamn.setText(svar1);
       lblRas.setText(svar2);
       lblRegDatum.setText(svar3);
       lblPlats.setText(svar4);
       lblTelefon.setText(svar5);
       lblLosenord.setText(svar6);
       lblID.setText(svar7);
       lblAnsvarigAgent.setText(svar8);
       
        }
        catch (InfException ex) {
            Logger.getLogger(InloggningsTyp.class.getName()).log(Level.SEVERE, null, ex);
            System.out.println("Ett fel har uppstått " + ex);
        }
    }
    
    public void setInfo (String namn)
    {
       lblNamn.setText(visaNamn(namn));
       lblRas.setText(visaRas(namn));
       lblRegDatum.setText(visaRegDatum(namn));
       lblPlats.setText(visaPlats(namn));
       lblTelefon.setText(visaTelefon(namn));
       lblLosenord.setText(visaLosenord(namn));
       lblID.setText(visaID(namn));
       lblAnsvarigAgent.setText(visaAnsvarigAgent(namn));
    }
    
    public void setNuvarandeUtomjording(String namn)
    {
        this.nuvarandeUtomjording = namn;
    }
    
    public String visaNamn (String namn)
    {
        String namnet = "";
        
        try {
        String fraga = "Select namn from alien where namn = '" + namn + "'";
        String svar = idb.fetchSingle(fraga);
        namnet = svar;
        }
        
        catch (InfException ex) {
            Logger.getLogger(InloggningsTyp.class.getName()).log(Level.SEVERE, null, ex);
            System.out.println("Ett fel har uppstått " + ex);
        }
        
        return namnet;
    }
    
    public String visaRegDatum (String namn)
    {
        String regDatum = "";
        
        try {
        String fraga = "Select Registreringsdatum from alien where namn = '" + namn + "'";
        String svar = idb.fetchSingle(fraga);
        regDatum = svar;
        }
        
        catch (InfException ex) {
            Logger.getLogger(InloggningsTyp.class.getName()).log(Level.SEVERE, null, ex);
            System.out.println("Ett fel har uppstått " + ex);
        }
        
        return regDatum;
    }
    
    public String visaPlats (String namn)
    {
        String plats = "";
        
        try {
        String fraga = "Select benamning from plats where plats_id = (Select Plats from alien where namn = '" + namn + "')";
        String svar = idb.fetchSingle(fraga);
        plats = svar;
        }
        
        catch (InfException ex) {
            Logger.getLogger(InloggningsTyp.class.getName()).log(Level.SEVERE, null, ex);
            System.out.println("Ett fel har uppstått " + ex);
        }
        
        return plats;
    }
    
    public String visaTelefon (String namn)
    {
        String telefon = "";
        
        try {
        String fraga = "Select telefon from alien where namn = '" + namn + "'";
        String svar = idb.fetchSingle(fraga);
        telefon = svar;
        }
        
        catch (InfException ex) {
            Logger.getLogger(InloggningsTyp.class.getName()).log(Level.SEVERE, null, ex);
            System.out.println("Ett fel har uppstått " + ex);
        }
        
        return telefon;
    }
    
    public String visaLosenord (String namn)
    {
        String losenord = "";
        
        try {
        String fraga = "Select losenord from alien where namn = '" + namn + "'";
        String svar = idb.fetchSingle(fraga);
        losenord = svar;
        }
        
        catch (InfException ex) {
            Logger.getLogger(InloggningsTyp.class.getName()).log(Level.SEVERE, null, ex);
            System.out.println("Ett fel har uppstått " + ex);
        }
        
        return losenord;
    }
    
    public String visaID (String namn)
    {
        String iD = "";
        
        try {
        String fraga = "Select alien_id from alien where namn = '" + namn + "'";
        String svar = idb.fetchSingle(fraga);
        iD = svar;
        }
        
        catch (InfException ex) {
            Logger.getLogger(InloggningsTyp.class.getName()).log(Level.SEVERE, null, ex);
            System.out.println("Ett fel har uppstått " + ex);
        }
        
        return iD;
    }
    
    public String visaAnsvarigAgent (String namn)
    {
        String Agent = "";
        
        try {
        String fraga = "Select namn from agent where agent_id = (Select Ansvarig_Agent from alien where namn = '" + namn + "')";
        String svar = idb.fetchSingle(fraga);
        Agent = svar;
        }
        
        catch (InfException ex) {
            Logger.getLogger(InloggningsTyp.class.getName()).log(Level.SEVERE, null, ex);
            System.out.println("Ett fel har uppstått " + ex);
        }
        
        return Agent;
    }
    
    public String visaRas (String utomjording)
    {
        boolean isBoglodite = false;
        boolean isWorm = false;
        boolean isSquid = false;
        String ras = "";

        try {
            String fraga = "Select alien_id from alien where namn = '" + utomjording + "'";
            String svarID = idb.fetchSingle(fraga);

            String fragaBoglodite = "Select alien_id from boglodite";
            ArrayList<String> boglodite = idb.fetchColumn(fragaBoglodite);

            String fragaWorm = "Select alien_id from worm";
            ArrayList<String> worm = idb.fetchColumn(fragaWorm);

            String fragaSquid = "Select alien_id from squid";
            ArrayList<String> squid = idb.fetchColumn(fragaSquid);

            for (String id : boglodite) {
                System.out.print(id);
                if (id.equals(svarID)) {
                    isBoglodite = true;
                    break;
                }
            }

            if (isBoglodite == false) {
                for (String id : worm) {
                    System.out.print(id);
                    if (id.equals(svarID)) {
                        isWorm = true;
                        break;
                    }
                }
            }

            if (isWorm == false && isBoglodite == false) {
                for (String id : squid) {
                    System.out.print(id);
                    if (id.equals(svarID)) {
                        isSquid = true;
                        break;

                    }
                }
            }
            
            if (isBoglodite == true) {
            ras = "Boglodite";
            String fraga1 = "Select antal_boogies from boglodite";
            String svar1 = idb.fetchSingle(fraga1);
            lblRasExtra.setText(svar1);
            lblRasExtraRubrik.setText("Antal boogies:");
            
        } else if (isWorm == true) {
            ras = "Worm";
            lblRasExtra.setText("");
            lblRasExtraRubrik.setText("");
        } else if (isSquid == true) {
            ras = "Squid";
            String fraga1 = "Select Antal_armar from squid";
            String svar1 = idb.fetchSingle(fraga1);
            lblRasExtra.setText(svar1);
            lblRasExtraRubrik.setText("Antal armar:");
        } else {
            System.out.println("Ingen ras hittad");
        }
        } catch (InfException ex) {
            Logger.getLogger(InloggningsTyp.class.getName()).log(Level.SEVERE, null, ex);
            System.out.println("Ett fel har uppstått " + ex);
        }

        
        return ras;
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnTillbaka;
    private javax.swing.JButton btnTillbakaTillHuvudmeny;
    private javax.swing.JLabel lblAnsvarigAgent;
    private javax.swing.JLabel lblAnsvarigAgentRubrik;
    private javax.swing.JLabel lblHuvudText;
    private javax.swing.JLabel lblID;
    private javax.swing.JLabel lblIDRubrik;
    private javax.swing.JLabel lblLosenord;
    private javax.swing.JLabel lblLosenordRubrik;
    private javax.swing.JLabel lblNamn;
    private javax.swing.JLabel lblNamnRubrik;
    private javax.swing.JLabel lblPlats;
    private javax.swing.JLabel lblPlatsRubrik;
    private javax.swing.JLabel lblRas;
    private javax.swing.JLabel lblRasExtra;
    private javax.swing.JLabel lblRasExtraRubrik;
    private javax.swing.JLabel lblRasRubrik;
    private javax.swing.JLabel lblRegDatum;
    private javax.swing.JLabel lblRegistreringsDatumRubrik;
    private javax.swing.JLabel lblTelefon;
    private javax.swing.JLabel lblTelefonRubrik;
    // End of variables declaration//GEN-END:variables
}
